title: Roshni Pandit
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 I love what programming can do with data and want to apply my software development skills to learn interesting things from it.
  <br>
  I am a Data-Focused Software Engineer. 
  <br>
  Data Engineer Intern,Shoptaki Inc(July 2020-Present)
  <br>
  Business Intelligence Intern,Infogain Pvt.Ltd(May 2017-Aug 2017)
  <br>
  Software Development Intern,Tata Consultancy Services(May 2016-Aug 2016)
  <br><br>
  
  <a href="https://www.linkedin.com/in/roshni-pandit-66b9ba13a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

