title: Roshni Pandit
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 I love what programming can do with data and want to apply my software development skills to learn interesting things from it.
  <br><br>
  Data-Focused Software Engineer 
  <br><br>
  <a href="https://www.linkedin.com/in/roshni-pandit-66b9ba13a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

